services:
  zarpa-api:
    image: ${DOCKERHUB_USER}/zarpa-api:latest
    container_name: zarpa-api
    restart: unless-stopped
    environment:
      - PORT=3000
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_SYNC=${TYPEORM_SYNC}
      - TYPEORM_SSLMODE=${TYPEORM_SSLMODE}
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.zarpa.rule=Host(\`zarpa.arcobatrox.com.br\`) && PathPrefix(\`/api\`)
      - traefik.http.routers.zarpa.entrypoints=websecure
      - traefik.http.routers.zarpa.service=zarpa-api
      - traefik.http.routers.zarpa.tls.certresolver=letsencryptresolver
      - traefik.http.services.zarpa.loadbalancer.passHostHeader=true
      - traefik.http.services.zarpa.loadbalancer.server.port=3000
      - traefik.http.middlewares.zarpa-strip-prefix.stripprefix.prefixes=/api
      - traefik.http.routers.zarpa.middlewares=zarpa-strip-prefix

networks:
  default:
    name: arcobatroxnet
    external: true
