services:
  zarpa-db:
   image: postgres:17.1-alpine
   container_name: zarpa-db
   ports:
    - '5433:5432'
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=zarpa
   networks:
    - app-networks
  
  zarpa-api:
   build: .
   container_name: zarpa-api
   ports:
     - "3000:3000"
   environment:
     - API_BASE_URL="http://localhost:3000"
     - WEB_BASE_URL="http://localhost:3333"
     - PORT=3000
     - JWT_SECRET=${JWT_SECRET}
    #  - DATABASE_URL="postgresql://postgres:postgres@localhost:5433/planner-vercel"
     - TYPEORM_HOST='${TYPEORM_HOST}'
     - TYPEORM_PORT=5432
     - TYPEORM_USERNAME='${TYPEORM_USERNAME}'
     - TYPEORM_PASSWORD='${TYPEORM_PASSWORD}'
     - TYPEORM_DATABASE='planner-vercel'
     - TYPEORM_SYNC=true
     - TYPEORM_LOGGING=true
   networks:
    - app-networks
   depends_on:
    - zarpa-db

networks:
  app-networks:
    driver: bridge