# Versão alternativa usando Webhook do Portainer (mais simples)

name: CI/CD Deploy via Portainer Webhook

on:
  push:
   branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USER }}/arcobatrip-api:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Trigger Portainer Webhook
        run: |
          curl -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
          echo "✅ Webhook enviado para Portainer"

      - name: Wait for deployment
        run: |
          echo "⏳ Aguardando 30 segundos para o deploy..."
          sleep 30

      - name: Verify deployment
        run: |
          echo "🔍 Verificando se a aplicação está respondendo..."
          curl -f "https://arcobatrip.arcobatrox.com.br/api/health" || echo "❌ Aplicação não está respondendo ainda"
