apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arcobatrip-api
  namespace: arcobatrip
  labels:
    app.kubernetes.io/part-of: arcobatrox
spec:
  secretName: arcobatrip-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: arcobatrip.arcobatrox.com.br
  dnsNames:
  - arcobatrip.arcobatrox.com.br
  - www.arcobatrip.arcobatrox.com.br