apiVersion: v1
kind: ConfigMap
metadata:
  name: arcobatrip-config
  namespace: arcobatrip
  labels:
    app.kubernetes.io/name: arcobatrip-api
    app.kubernetes.io/part-of: arcobatrox
data:
  NODE_ENV: "production"
  PORT: "3000"
  TZ: "America/Sao_Paulo"
  LOG_LEVEL: "info"
  APP_NAME: "arcobatrip-api"