apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcobatrip-api
  namespace: arcobatrip
  labels:
    app: arcobatrip-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcobatrip-api
  template:
    metadata:
      labels:
        app: arcobatrip-api
    spec:
      containers:
        - name: backend
          image: REPLACE_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: arcobatrip-config
            - secretRef:
                name: arcobatrip-secret
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
