apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: arcobatrip-backend-hpa
  namespace: arcobatrip
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: arcobatrip-backend
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
