apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zarpa-api-hpa
  namespace: zarpa
  labels:
    app.kubernetes.io/name: zarpa-api
    app.kubernetes.io/part-of: arcobatrox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zarpa-api
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
