apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zarpa-api-ingress
  namespace: zarpa
  labels:
    app.kubernetes.io/name: zarpa-api
    app.kubernetes.io/part-of: arcobatrox
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`zarpa.arcobatrox.com.br`) && PathPrefix(`/api/v1`)
      kind: Rule
      services:
        - name: zarpa-api
          port: 80
    - match: Host(`www.zarpa.arcobatrox.com.br`) && PathPrefix(`/api/v1`)
      kind: Rule
      services:
        - name: zarpa-api
          port: 80
  tls:
    secretName: zarpa-tls
