apiVersion: v1
kind: Namespace
metadata:
  name: arcobatrip
  labels:
    app.kubernetes.io/name: arcobatrip
    app.kubernetes.io/part-of: arcobatrox
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/enforce: restricted
