apiVersion: v1
kind: Namespace
metadata:
  name: zarpa
  labels:
    app.kubernetes.io/name: zarpa
    app.kubernetes.io/part-of: arcobatrox
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/enforce: restricted
