apiVersion: v1
kind: Service
metadata:
  name: zarpa-api
  namespace: zarpa
  labels:
    app.kubernetes.io/name: zarpa-api
    app.kubernetes.io/part-of: arcobatrox
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zarpa-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
