apiVersion: v1
kind: Service
metadata:
  name: arcobatrip-api
  namespace: arcobatrip
spec:
  type: ClusterIP
  selector:
    app: arcobatrip-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
