apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zarpa-api
  namespace: zarpa
  labels:
    app.kubernetes.io/part-of: arcobatrox
spec:
  secretName: zarpa-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: zarpa.arcobatrox.com.br
  dnsNames:
  - zarpa.arcobatrox.com.br
  - www.zarpa.arcobatrox.com.br