name: CI/CD Deploy to VPS with Portainer

on:
  push:
   branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USER }}/arcobatrip-api:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
         host: ${{ secrets.VPS_HOST }}
         username: ${{ secrets.VPS_USER }}
         key: ${{ secrets.VPS_KEY }}
         script: |
           docker pull ${{ secrets.DOCKERHUB_USER }}/arcobatrip-api:latest
           docker stop arcobatrip-api || true
           docker rm arcobatrip-api || true
           docker run -d --name arcobatrip-api \
             -p 3000:3000 \
             --network arcobatroxnet \
             --restart unless-stopped \
             -e PORT=3000 \
             -e TYPEORM_HOST=${{ secrets.TYPEORM_HOST }} \
             -e TYPEORM_PORT=${{ secrets.TYPEORM_PORT }} \
             -e TYPEORM_USERNAME=${{ secrets.TYPEORM_USERNAME }} \
             -e TYPEORM_PASSWORD=${{ secrets.TYPEORM_PASSWORD }} \
             -e TYPEORM_DATABASE=${{ secrets.TYPEORM_DATABASE }} \
             -e TYPEORM_SYNC=${{ secrets.TYPEORM_SYNC }} \
             -l traefik.enable=true \
             -l traefik.http.routers.arcobatrip.rule=Host\(`arcobatrip.arcobatrox.com.br`\) && PathPrefix\(`/api`\) \
             -l traefik.http.routers.arcobatrip.entrypoints=websecure \
             -l traefik.http.routers.arcobatrip.service=arcobatrip-api \
             -l traefik.http.routers.arcobatrip.tls.certresolver=letsencryptresolver \
             -l traefik.http.services.arcobatrip.loadbalancer.passHostHeader=true \
             -l traefik.http.services.arcobatrip.loadbalancer.server.port=3000 \
             -l traefik.http.middlewares.arcobatrip-strip-prefix.stripprefix.prefixes=/api \
             -l traefik.http.routers.arcobatrip.middlewares=arcobatrip-strip-prefix \
             ${{ secrets.DOCKERHUB_USER }}/arcobatrip-api:latest