name: CI/CD Deploy to VPS with K8s

on:
  push:
   branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USER }}/arcobatrip-api:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Prepare kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Criar namespace se não existir
        run: |
          kubectl get namespace arcobatrip || kubectl create namespace arcobatrip

      - name: Criar/atualizar secret no cluster
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            TYPEORM_HOST: ${{ secrets.TYPEORM_HOST }}
            TYPEORM_PORT: ${{ secrets.TYPEORM_PORT }}
            TYPEORM_USERNAME: ${{ secrets.TYPEORM_USERNAME }}
            TYPEORM_PASSWORD: ${{ secrets.TYPEORM_PASSWORD }}
            TYPEORM_DATABASE: ${{ secrets.TYPEORM_DATABASE }}
            TYPEORM_SYNC: ${{ secrets.TYPEORM_SYNC }}
            TYPEORM_LOGGING: ${{ secrets.TYPEORM_LOGGING }}
            TYPEORM_SSLMODE: 'require'

        run: |
          kubectl create secret generic arcobatrip-secret -n arcobatrip \
            --from-literal=DATABASE_URL="${DATABASE_URL}" \
            --from-literal=JWT_SECRET="${JWT_SECRET}" \
            --from-literal=TYPEORM_HOST="${TYPEORM_HOST}" \
            --from-literal=TYPEORM_PORT="${TYPEORM_PORT}" \
            --from-literal=TYPEORM_USERNAME="${TYPEORM_USERNAME}" \
            --from-literal=TYPEORM_PASSWORD="${TYPEORM_PASSWORD}" \
            --from-literal=TYPEORM_DATABASE="${TYPEORM_DATABASE}" \
            --from-literal=TYPEORM_SYNC="${TYPEORM_SYNC}" \
            --from-literal=TYPEORM_LOGGING="${TYPEORM_LOGGING}" \
            --from-literal=TYPEORM_SSLMODE="${TYPEORM_SSLMODE}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Replace image placeholder
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USER }}/arcobatrip-api:${{ github.sha }}
          sed -i "s|REPLACE_IMAGE|${IMAGE_NAME}|g" k8s/deployment.yaml

      - name: kubectl apply
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml || true
          kubectl apply -f k8s/arcobatrip-middlewares.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/ingress-route.yaml